#!/bin/bash

echo "Seelct SCP or SSH"

while :
do
read INPUT_STRING
case $INPUT_STRING in
   SCP)

       echo "selected SCP"
       echo "Provide username and ip"
       read username ip
       scp -r $username@$ip /home/$username
       ;;
   SSH)
       echo "selected SSH"
       echo "Provide the username and ip"
       read username ip
       ssh $username@$ip whoami
       ;;
   *)
       echo "Invalid argument"
       echo
       ;;
esac
done
